permalink: /20180304/Hello, World!
url: red1144.github.io
baseurl: /project

# variables
name: Ambiguity
description: It is ambiguous.
google_verification: ambiguity


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true